/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5db9c2cbc6ce4c4de2ba3317
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { DocumentsService } from '../../services/documents.service';
import { TasksService } from '../../services/tasks.service';
// Import Models
import { Documents } from '../../domain/easy-recruit_db/documents';
import { Tasks } from '../../domain/easy-recruit_db/tasks';

// START - USED SERVICES
/**
* DocumentsService.create
*	@description CRUD ACTION create
*
* DocumentsService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* TasksService.list
*	@description CRUD ACTION list
*
* DocumentsService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Documents
 */
@Component({
    selector: 'app-documents-edit',
    templateUrl: 'documents-edit.component.html',
    styleUrls: ['documents-edit.component.css']
})
export class DocumentsEditComponent implements OnInit {
    item: Documents;
    listTaskId: Tasks[];
    model: Documents;
    formValid: Boolean;

    constructor(
    private documentsService: DocumentsService,
    private tasksService: TasksService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Documents();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.documentsService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
            this.tasksService.list().subscribe(list => this.listTaskId = list);
        });
    }


    /**
     * Save Documents
     *
     * @param {boolean} formValid Form validity check
     * @param Documents item Documents to save
     */
    save(formValid: boolean, item: Documents): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.documentsService.update(item).subscribe(data => this.goBack());
            } else {
                this.documentsService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



