/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5db9c2cbc6ce4c4de2ba3317
*
* You will get 10% discount for each one of your friends
* 
*/
// DEPENDENCIES
import { NgModule } from '@angular/core';
import { CanActivate, RouterModule, Routes } from '@angular/router';

/* START MY VIEWS IMPORT */
// Do not edit this comment content, it will be overwritten in next Skaffolder generation
import { HomeComponent} from './pages/home/home.component';
import { CandidateEditComponent} from './pages/candidate-edit/candidate-edit.component';
import { CandidateListComponent} from './pages/candidate-list/candidate-list.component';
import { DocumentsEditComponent} from './pages/documents-edit/documents-edit.component';
import { DocumentsListComponent} from './pages/documents-list/documents-list.component';
import { TaskListEditComponent} from './pages/task-list-edit/task-list-edit.component';
import { TaskListListComponent} from './pages/task-list-list/task-list-list.component';
import { TasksEditComponent} from './pages/tasks-edit/tasks-edit.component';
import { TasksListComponent} from './pages/tasks-list/tasks-list.component';
import { UserEditComponent} from './pages/user-edit/user-edit.component';
import { UserListComponent} from './pages/user-list/user-list.component';

/* END MY VIEWS IMPORT */

// SECURITY
import { LoginComponent } from './pages/login/login.component';
import { ManageUserEditComponent } from './security/manage-user/edit-user/manage-user-edit.component';
import { ManageUserListComponent } from './security/manage-user/list-user/manage-user-list.component';
import { ProfileComponent } from './security/profile/profile.component';
import { AuthGuard } from './security/auth.guard';

/**
 * WEB APP ROUTES
 */
const routes: Routes = [
    { path: '', redirectTo: '/home', pathMatch: 'full'  },

    /* START MY VIEWS */

    { path: 'candidates/:id',  loadChildren: './pages/candidate-edit/candidate-edit.module#CandidateEditModule' , canActivate: [AuthGuard] },
    { path: 'candidates',  loadChildren: './pages/candidate-list/candidate-list.module#CandidateListModule' , canActivate: [AuthGuard] },
    { path: 'documentses/:id',  loadChildren: './pages/documents-edit/documents-edit.module#DocumentsEditModule' , canActivate: [AuthGuard] },
    { path: 'documentses',  loadChildren: './pages/documents-list/documents-list.module#DocumentsListModule' , canActivate: [AuthGuard] },
    { path: 'home',  loadChildren: './pages/home/home.module#HomeModule' , canActivate: [AuthGuard] },
    { path: 'tasklists/:id',  loadChildren: './pages/task-list-edit/task-list-edit.module#TaskListEditModule' , canActivate: [AuthGuard] },
    { path: 'tasklists',  loadChildren: './pages/task-list-list/task-list-list.module#TaskListListModule' , canActivate: [AuthGuard] },
    { path: 'taskses/:id',  loadChildren: './pages/tasks-edit/tasks-edit.module#TasksEditModule' , canActivate: [AuthGuard] },
    { path: 'taskses',  loadChildren: './pages/tasks-list/tasks-list.module#TasksListModule' , canActivate: [AuthGuard] },
    { path: 'users/:id',  loadChildren: './pages/user-edit/user-edit.module#UserEditModule' , canActivate: [AuthGuard] },
    { path: 'users',  loadChildren: './pages/user-list/user-list.module#UserListModule' , canActivate: [AuthGuard] },

 /* END MY VIEWS */

    // SECURITY
    { path: 'manage-users',  loadChildren: './security/manage-user/list-user/manage-user-list.module#ManageUserListModule', canActivate: [AuthGuard], data: ['ADMIN']},
    { path: 'manage-users/:id',  loadChildren: './security/manage-user/edit-user/manage-user-edit.module#ManageUserEditModule', canActivate: [AuthGuard], data: ['ADMIN']},
    { path: 'profile',  loadChildren: './security/profile/profile.module#ProfileModule', canActivate: [AuthGuard] },
    { path: 'login', loadChildren: './pages/login/login.module#LoginModule'}
];

/**
 * ROUTING MODULE
 */
@NgModule({
    imports: [ RouterModule.forRoot(routes) ],
    exports: [ RouterModule ]
})

export class AppRoutingModule {}
