/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5db9c2cbc6ce4c4de2ba3317
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { DocumentsService } from '../../services/documents.service';
// Import Models
import { Documents } from '../../domain/easy-recruit_db/documents';

// START - USED SERVICES
/**
* DocumentsService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* DocumentsService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Documents
 * @class DocumentsListComponent
 */
@Component({
    selector: 'app-documents-list',
    templateUrl: './documents-list.component.html',
    styleUrls: ['./documents-list.component.css']
})
export class DocumentsListComponent implements OnInit {
    list: Documents[];
    search: any = {};
    idSelected: string;
    constructor(
        private documentsService: DocumentsService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.documentsService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Documents to remove
     *
     * @param {string} id Id of the Documents to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Documents
     */
    deleteItem() {
        this.documentsService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
